MY_TARGETS=scalar 1D_arr_global 1D_arr_global_noxml maya_append maya_noxml
MY_MAKEFILE=Makefile.generic

.PHONY: all clean clean_test run-r-flx run-w-flx run-r-mpi run-w-mpi

all: $(MY_TARGETS)
	@$(MAKE) -f $(MY_MAKEFILE) -C scalar $@;
	@$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@;
	@$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@;
	@$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@;
	@$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@;
	
	
	 
clean_test: 
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@
	
clean: $(MY_TARGETS)
	$(MAKE) -f $(MY_MAKEFILE) -C scalar $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@

run-r-flx:
	$(MAKE) -f $(MY_MAKEFILE) -C scalar $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@
#	$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@
#	$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@
	
run-w-flx:
	$(MAKE) -f $(MY_MAKEFILE) -C scalar $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@
#	$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@
#	$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@

run-r-mpi:
	$(MAKE) -f $(MY_MAKEFILE) -C scalar $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@
	
run-w-mpi:
	$(MAKE) -f $(MY_MAKEFILE) -C scalar $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global $@
	$(MAKE) -f $(MY_MAKEFILE) -C 1D_arr_global_noxml $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_append $@
	$(MAKE) -f $(MY_MAKEFILE) -C maya_noxml $@
