include make.settings

## Set ADIOS_DIR here or before doing make
override ADIOS_INC=`${ADIOS_DIR}/bin/adios_config -c -f`
override ADIOS_FLIB=`${ADIOS_DIR}/bin/adios_config -l -f`

default: genarray_stream
all: default

genarray_stream.o : genarray_stream.F90 
	${FC} -g -c ${ADIOS_INC} genarray_stream.F90  $<

genarray_stream:  genarray_stream.o
	${FC} -g -o genarray_stream genarray_stream.o ${ADIOS_FLIB} 


clean:
	rm -f *.o *.mod *.fh core.*
	rm -f genarray_stream

distclean: clean

