#!/bin/sh
#PBS -A CSC025ewk
#PBS -N chimera_xxxx_mmmm_nnnn
#PBS -o wwww/chimera_run/xxxx/mmmm/nnnn/Execute/build/run.stdout
#PBS -e wwww/chimera_run/xxxx/mmmm/nnnn/Execute/build/run.stderr
#PBS -l walltime=04:00:00,size=xxxx

cd wwww/chimera_run/xxxx/mmmm/nnnn/Execute/build

# copy initial parameter files
cp -rf wwww/chimera_setting/xxxx/Initial_Data/* ./Data3/Initial_Data
sed -i.bak -e "s/dddd/xxxx\/mmmm\/nnnn/" ./Data3/Initial_Data/array_dimensions.d

# copy config.xml file
cp -rf wwww/chimera_setting/configfile/mmmm ./config.xml

# write log file
echo "Test Chimera on Machine ""$(hostname)" > ./log
date >> ./log
echo "nproc=""xxxx" >> ./log
echo "method=""mmmm" >> ./log
echo "testno=""nnnn" >> ./log
echo >> ./log
echo "Initial Parameter" >> ./log
grep "^n" Data3/Initial_Data/array_dimensions.d >> ./log
grep "ncymax$" Data3/Initial_Data/radhyd_keys.d >> ./log
grep "intprm$" Data3/Initial_Data/edit_keys.d >> ./log
echo >> ./log

echo "Run Chimera begin" >> ./log
date >> ./log

# run the simulation
aprun -n xxxx ./RadHyd3D >runlog 2>&1

echo "Run Chimera end" >> ./log
date >> ./log
echo >> ./log

# collect timing info
echo "Restart files" >> ./log
ls -l Data3/Restart/ >> ./log
echo >> ./log
mkdir -p wwww/chimera_results/xxxx/mmmm/nnnn
cp ./log wwww/chimera_results/xxxx/mmmm/nnnn/log
cp ./runlog wwww/chimera_results/xxxx/mmmm/nnnn/runlog
if [ -f run.stdout ]
then
  cp -rf run.stdout wwww/chimera_results/xxxx/mmmm/nnnn
fi
if [ -f run.stderr ]
then
  cp -rf run.stderr wwww/chimera_results/xxxx/mmmm/nnnn
fi

# cleanup
sh Data3/cleanup

