/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.adioslib;

public class _ADIOS_VARSTAT {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _ADIOS_VARSTAT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_ADIOS_VARSTAT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        adioslibJNI.delete__ADIOS_VARSTAT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSteps(ADIOS_STAT_STEP value) {
    adioslibJNI._ADIOS_VARSTAT_steps_set(swigCPtr, this, ADIOS_STAT_STEP.getCPtr(value), value);
  }

  public ADIOS_STAT_STEP getSteps() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_steps_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ADIOS_STAT_STEP(cPtr, false);
  }

  public void setBlocks(ADIOS_STAT_BLOCK value) {
    adioslibJNI._ADIOS_VARSTAT_blocks_set(swigCPtr, this, ADIOS_STAT_BLOCK.getCPtr(value), value);
  }

  public ADIOS_STAT_BLOCK getBlocks() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_blocks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ADIOS_STAT_BLOCK(cPtr, false);
  }

  public void setHistogram(ADIOS_HIST value) {
    adioslibJNI._ADIOS_VARSTAT_histogram_set(swigCPtr, this, ADIOS_HIST.getCPtr(value), value);
  }

  public ADIOS_HIST getHistogram() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_histogram_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ADIOS_HIST(cPtr, false);
  }

  public void setMin(SWIGTYPE_p_void value) {
    adioslibJNI._ADIOS_VARSTAT_min_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getMin() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setMax(SWIGTYPE_p_void value) {
    adioslibJNI._ADIOS_VARSTAT_max_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getMax() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setAvg(SWIGTYPE_p_double value) {
    adioslibJNI._ADIOS_VARSTAT_avg_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getAvg() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_avg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setStd_dev(SWIGTYPE_p_double value) {
    adioslibJNI._ADIOS_VARSTAT_std_dev_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getStd_dev() {
    long cPtr = adioslibJNI._ADIOS_VARSTAT_std_dev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public _ADIOS_VARSTAT() {
    this(adioslibJNI.new__ADIOS_VARSTAT(), true);
  }

}
