/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.adioslib;

public class ADIOS_STAT_STEP {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ADIOS_STAT_STEP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADIOS_STAT_STEP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        adioslibJNI.delete_ADIOS_STAT_STEP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMins(SWIGTYPE_p_p_void value) {
    adioslibJNI.ADIOS_STAT_STEP_mins_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getMins() {
    long cPtr = adioslibJNI.ADIOS_STAT_STEP_mins_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public void setMaxs(SWIGTYPE_p_p_void value) {
    adioslibJNI.ADIOS_STAT_STEP_maxs_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getMaxs() {
    long cPtr = adioslibJNI.ADIOS_STAT_STEP_maxs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public void setAvgs(SWIGTYPE_p_p_double value) {
    adioslibJNI.ADIOS_STAT_STEP_avgs_set(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_p_double getAvgs() {
    long cPtr = adioslibJNI.ADIOS_STAT_STEP_avgs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public void setStd_devs(SWIGTYPE_p_p_double value) {
    adioslibJNI.ADIOS_STAT_STEP_std_devs_set(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_p_double getStd_devs() {
    long cPtr = adioslibJNI.ADIOS_STAT_STEP_std_devs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public ADIOS_STAT_STEP() {
    this(adioslibJNI.new_ADIOS_STAT_STEP(), true);
  }

}
