/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.adioslib;

public enum ADIOS_STATISTICS_FLAG {
  adios_stat_no(adioslibJNI.adios_stat_no_get()),
  adios_stat_minmax(adioslibJNI.adios_stat_minmax_get()),
  adios_stat_full(adioslibJNI.adios_stat_full_get()),
  adios_stat_default(adioslibJNI.adios_stat_default_get()),
  adios_stat_no_do_not_use_this(adioslibJNI.adios_stat_no_do_not_use_this_get());

  public final int swigValue() {
    return swigValue;
  }

  public static ADIOS_STATISTICS_FLAG swigToEnum(int swigValue) {
    ADIOS_STATISTICS_FLAG[] swigValues = ADIOS_STATISTICS_FLAG.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ADIOS_STATISTICS_FLAG swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ADIOS_STATISTICS_FLAG.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ADIOS_STATISTICS_FLAG() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ADIOS_STATISTICS_FLAG(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ADIOS_STATISTICS_FLAG(ADIOS_STATISTICS_FLAG swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

