/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.adioslib;

public class ADIOS_FILE {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ADIOS_FILE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADIOS_FILE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        adioslibJNI.delete_ADIOS_FILE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFh(java.math.BigInteger value) {
    adioslibJNI.ADIOS_FILE_fh_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getFh() {
    return adioslibJNI.ADIOS_FILE_fh_get(swigCPtr, this);
  }

  public void setNvars(int value) {
    adioslibJNI.ADIOS_FILE_nvars_set(swigCPtr, this, value);
  }

  public int getNvars() {
    return adioslibJNI.ADIOS_FILE_nvars_get(swigCPtr, this);
  }

  public void setVar_namelist(String[] value) {
    adioslibJNI.ADIOS_FILE_var_namelist_set(swigCPtr, this, value);
  }

  public String[] getVar_namelist() {
    return adioslibJNI.ADIOS_FILE_var_namelist_get(swigCPtr, this);
}

  public void setNattrs(int value) {
    adioslibJNI.ADIOS_FILE_nattrs_set(swigCPtr, this, value);
  }

  public int getNattrs() {
    return adioslibJNI.ADIOS_FILE_nattrs_get(swigCPtr, this);
  }

  public void setAttr_namelist(String[] value) {
    adioslibJNI.ADIOS_FILE_attr_namelist_set(swigCPtr, this, value);
  }

  public String[] getAttr_namelist() {
    return adioslibJNI.ADIOS_FILE_attr_namelist_get(swigCPtr, this);
}

  public void setNmeshes(int value) {
    adioslibJNI.ADIOS_FILE_nmeshes_set(swigCPtr, this, value);
  }

  public int getNmeshes() {
    return adioslibJNI.ADIOS_FILE_nmeshes_get(swigCPtr, this);
  }

  public void setMesh_namelist(SWIGTYPE_p_p_char value) {
    adioslibJNI.ADIOS_FILE_mesh_namelist_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getMesh_namelist() {
    long cPtr = adioslibJNI.ADIOS_FILE_mesh_namelist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setNlinks(int value) {
    adioslibJNI.ADIOS_FILE_nlinks_set(swigCPtr, this, value);
  }

  public int getNlinks() {
    return adioslibJNI.ADIOS_FILE_nlinks_get(swigCPtr, this);
  }

  public void setLink_namelist(SWIGTYPE_p_p_char value) {
    adioslibJNI.ADIOS_FILE_link_namelist_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getLink_namelist() {
    long cPtr = adioslibJNI.ADIOS_FILE_link_namelist_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setCurrent_step(int value) {
    adioslibJNI.ADIOS_FILE_current_step_set(swigCPtr, this, value);
  }

  public int getCurrent_step() {
    return adioslibJNI.ADIOS_FILE_current_step_get(swigCPtr, this);
  }

  public void setLast_step(int value) {
    adioslibJNI.ADIOS_FILE_last_step_set(swigCPtr, this, value);
  }

  public int getLast_step() {
    return adioslibJNI.ADIOS_FILE_last_step_get(swigCPtr, this);
  }

  public void setIs_streaming(int value) {
    adioslibJNI.ADIOS_FILE_is_streaming_set(swigCPtr, this, value);
  }

  public int getIs_streaming() {
    return adioslibJNI.ADIOS_FILE_is_streaming_get(swigCPtr, this);
  }

  public void setPath(String value) {
    adioslibJNI.ADIOS_FILE_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return adioslibJNI.ADIOS_FILE_path_get(swigCPtr, this);
  }

  public void setEndianness(int value) {
    adioslibJNI.ADIOS_FILE_endianness_set(swigCPtr, this, value);
  }

  public int getEndianness() {
    return adioslibJNI.ADIOS_FILE_endianness_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    adioslibJNI.ADIOS_FILE_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return adioslibJNI.ADIOS_FILE_version_get(swigCPtr, this);
  }

  public void setFile_size(java.math.BigInteger value) {
    adioslibJNI.ADIOS_FILE_file_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getFile_size() {
    return adioslibJNI.ADIOS_FILE_file_size_get(swigCPtr, this);
  }

  public void setInternal_data(SWIGTYPE_p_void value) {
    adioslibJNI.ADIOS_FILE_internal_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getInternal_data() {
    long cPtr = adioslibJNI.ADIOS_FILE_internal_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ADIOS_FILE() {
    this(adioslibJNI.new_ADIOS_FILE(), true);
  }

}
