/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.adioslib;

public enum ADIOS_DATATYPES {
  adios_unknown(adioslibJNI.adios_unknown_get()),
  adios_byte(adioslibJNI.adios_byte_get()),
  adios_short(adioslibJNI.adios_short_get()),
  adios_integer(adioslibJNI.adios_integer_get()),
  adios_long(adioslibJNI.adios_long_get()),
  adios_unsigned_byte(adioslibJNI.adios_unsigned_byte_get()),
  adios_unsigned_short(adioslibJNI.adios_unsigned_short_get()),
  adios_unsigned_integer(adioslibJNI.adios_unsigned_integer_get()),
  adios_unsigned_long(adioslibJNI.adios_unsigned_long_get()),
  adios_real(adioslibJNI.adios_real_get()),
  adios_double(adioslibJNI.adios_double_get()),
  adios_long_double(adioslibJNI.adios_long_double_get()),
  adios_string(adioslibJNI.adios_string_get()),
  adios_complex(adioslibJNI.adios_complex_get()),
  adios_double_complex(adioslibJNI.adios_double_complex_get()),
  adios_string_array(adioslibJNI.adios_string_array_get());

  public final int swigValue() {
    return swigValue;
  }

  public static ADIOS_DATATYPES swigToEnum(int swigValue) {
    ADIOS_DATATYPES[] swigValues = ADIOS_DATATYPES.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ADIOS_DATATYPES swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ADIOS_DATATYPES.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ADIOS_DATATYPES() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ADIOS_DATATYPES(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ADIOS_DATATYPES(ADIOS_DATATYPES swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

