       INTEGER MPI_LOGICAL
       INTEGER MPI_INTEGER
       INTEGER MPI_REAL
       INTEGER MPI_DOUBLE_PRECISION
       INTEGER MPI_2DOUBLE_PRECISION
       INTEGER MPI_CHARACTER
       INTEGER MPI_BYTE
       PARAMETER (MPI_LOGICAL=0,MPI_INTEGER=1,MPI_REAL=2)
       PARAMETER (MPI_DOUBLE_PRECISION=3)
       PARAMETER (MPI_2DOUBLE_PRECISION=4)
       PARAMETER (MPI_CHARACTER=5)
       PARAMETER (MPI_BYTE=5)

       INTEGER MPI_SUCCESS
       INTEGER MPI_FAILURE
       PARAMETER (MPI_SUCCESS=0,MPI_FAILURE=1)

       INTEGER MPI_COMM_WORLD
       PARAMETER (MPI_COMM_WORLD=1)

       INTEGER MPI_MINLOC 
       INTEGER MPI_MAXLOC 
       INTEGER MPI_MIN
       INTEGER MPI_MAX
       INTEGER MPI_SUM
       INTEGER MPI_LOR
       PARAMETER (MPI_MINLOC=1, MPI_MAXLOC=2)
       PARAMETER (MPI_MIN=3,MPI_MAX=4,MPI_SUM=5,MPI_LOR=6)

       EXTERNAL MPI_WTIME
       DOUBLE PRECISION MPI_WTIME


       INTEGER MPI_STATUS_SIZE
       PARAMETER (MPI_STATUS_SIZE=4)
       INTEGER MPI_TAG
       PARAMETER (MPI_TAG=4)
       INTEGER MPI_SOURCE
       PARAMETER (MPI_SOURCE=4)
       INTEGER MPI_PROC_NULL
       PARAMETER (MPI_PROC_NULL=999)


       INTEGER MPI_ANY_SOURCE
       INTEGER MPI_ANY_TAG
       PARAMETER (MPI_ANY_SOURCE=999,MPI_ANY_TAG=999)

