#!/bin/bash
#PBS -N xgc 
#PBS -A stf006 
#PBS -j oe
#PBS -q batch
#PBS -l walltime=00:30:00,size=32

cd $PBS_O_WORKDIR

aprun -n 32 ~cgj/adios/ADIOS/trunk/applications/xgc1/src/xgc1 >& results.dat

# post run cleanup
touch finished.sim
