#ifndef ADIOS_TRANSFORM_BLOSC_COMMON_H
#define ADIOS_TRANSFORM_BLOSC_COMMON_H

#include "blosc.h"

typedef int32_t adiosBloscSize_t;

#define ADIOS_BLOSC_MAX_INPUT_SIZE BLOSC_MAX_BUFFERSIZE
#define ADIOS_BLOSC_MAX_OVERHEAD BLOSC_MAX_OVERHEAD
#define ADIOS_BLOSC_MAX_TYPESIZE BLOSC_MAX_TYPESIZE

#endif /* ADIOS_TRANSFORM_BLOSC_COMMON_H */
