SHELL = /bin/sh

# clear out the suffix list
.SUFFIXES:
# define new suffixes
.SUFFIXES: .c .o
CC=cc

#ADIOS_ROOT=/rock/opt/adios/git-dbg
#MXML_ROOT=/rock/opt/mxml/2.7
#MPI_ROOT=/rock/opt/openmpi/1.6.3
#EVPATH_ROOT=/rock/opt/evpath
#LUSTRE_ROOT=/opt/cray/lustre-cray_ss_s/default

#LIBS=`/rock/opt/adios/1.5.0-dbg/bin/adios_config -l`
LIBS_PATHS=-L$(ADIOS_ROOT)/lib -L$(MXML_ROOT)/lib -L$(MPI_ROOT)/lib -L$(EVPATH_ROOT)/lib -L$(LUSTRE_ROOT)/lib64
LIBS=-ladios -ladiosread -lm -lmxml -levpath -latl -lcercs_env -lffs -ldill -lgen_thread -llustreapi
#INCLUDES=`/rock/opt/adios/1.5.0-dbg/bin/adios_config -c`
INCLUDES=-I../include -I$(ADIOS_ROOT)/include -I$(MXML_ROOT)/include -I$(MPI_ROOT)/include -I$(EVPATH_ROOT)/include -I$(LUSTRE_ROOT)/include

# $^ automatic var - source file whatever it is
# $@ output automatic var

all: reader writer

reader: reader.o  utils.o
	$(CC) $(CFLAGS) -g -o $@ $^ $(INCLUDES) $(LIBS_PATHS) $(LIBS) 
	 
writer: writer.o  utils.o
	$(CC) $(CFLAGS) -g -o $@ $^ $(INCLUDES) $(LIBS_PATHS) $(LIBS) 

.c.o: utils.h misc.h cfg.h
	$(CC) $(CFLAGS) -g -c $< -o $@ $(INCLUDES) $(LIBS_PATHS) $(LIBS)
	
	
run-w:
	./writer
	
run-r:
	./reader
		
clean_test:
	rm -rf test*.bp *_writer_info.txt *_reader_info.txt *_reader_ready.txt *_writer_ready.txt
	
clean:
	rm -rf reader writer  *.o

clean_all:
	$(MAKE) clean
	$(MAKE) clean_test
	
