#!/bin/sh
#PBS -A CSC025ewk
#PBS -N chimera_1024_POSIX_4
#PBS -o /tmp/work/zf2/chimera_run/1024/POSIX/4/Execute/build/run.stdout
#PBS -e /tmp/work/zf2/chimera_run/1024/POSIX/4/Execute/build/run.stderr
#PBS -l walltime=01:00:00,size=1024

cd /tmp/work/zf2/chimera_run/1024/POSIX/4/Execute/build

# copy initial parameter files
cp -rf /ccs/home/zf2/chimera_setting/1024/Initial_Data/* ./Data3/Initial_Data
sed -i.bak -e "s/dddd/1024\/POSIX\/4/" ./Data3/Initial_Data/array_dimensions.d

# copy config.xml file
cp -rf /ccs/home/zf2/chimera_setting/configfile/POSIX ./config.xml

# write log file
echo "Test Chimera on Machine ""$(hostname)" > ./log
date >> ./log
echo "nproc=""1024" >> ./log
echo "method=""POSIX" >> ./log
echo "testno=""4" >> ./log
echo >> ./log
echo "Initial Parameter" >> ./log
grep "^n" Data3/Initial_Data/array_dimensions.d >> ./log
grep "ncymax$" Data3/Initial_Data/radhyd_keys.d >> ./log
grep "intprm$" Data3/Initial_Data/edit_keys.d >> ./log
echo >> ./log

echo "Run Chimera begin" >> ./log
date >> ./log

# run the simulation
aprun -n 1024 ./RadHyd3D >runlog 2>&1

echo "Run Chimera end" >> ./log
date >> ./log
echo >> ./log

# collect timing info
echo "Restart files" >> ./log
ls -l Data3/Restart/ >> ./log
echo >> ./log
mkdir -p /tmp/work/zf2/chimera_results/1024/POSIX/4
cp ./log /tmp/work/zf2/chimera_results/1024/POSIX/4/log
cp ./runlog /tmp/work/zf2/chimera_results/1024/POSIX/4/runlog
if [ -f run.stdout ]
then
  cp -rf run.stdout /tmp/work/zf2/chimera_results/1024/POSIX/4
fi
if [ -f run.stderr ]
then
  cp -rf run.stderr /tmp/work/zf2/chimera_results/1024/POSIX/4
fi

# cleanup
sh Data3/cleanup

