# The protocol file generated by protogen.py ver. 1.0 on 2013-05-03 12:31
# AUTHOR: Magda S aka Magic Magg magg dot gatech at gmail dot com
# DATE: 2013-05-03

HOW TO RUN 
============


RUNNING ON KRAKEN
=================
This runs one reader per node and one writer per node.

aprun -n 1 -N 1 ./arrays_read &
aprun -n 1 -N 1 ./arrays_write

You should be able to run the example with as many readers and writers as you wish.

Example PBS script
------------------
#!/bash/bin
#PBS -l walltime=00:05:00,size=24
#PBS -A UT-TENN0033

date

echo "nodefile="
cat $PBS_NODEFILE
echo "=end nodefile"

# make sure you have all modules loaded
module use ~smagg/opt/modulefiles
module load mag-mxml-2.7/kraken-gnu
module list

cd $PBS_O_WORKDIR

aprun -n 1 -N 1 ./arrays_read &
aprun -n 1 -N 1 ./arrays_write

date

# eof


TROUBLESHOOTING
===============

There might be text files left; they should be removed for the next run.

# EOF
