/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public class _ADIOS_VARBLOCK {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _ADIOS_VARBLOCK(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_ADIOS_VARBLOCK obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        adioslibJNI.delete__ADIOS_VARBLOCK(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(SWIGTYPE_p_unsigned_long_long value) {
    adioslibJNI._ADIOS_VARBLOCK_start_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getStart() {
    long cPtr = adioslibJNI._ADIOS_VARBLOCK_start_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setCount(SWIGTYPE_p_unsigned_long_long value) {
    adioslibJNI._ADIOS_VARBLOCK_count_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getCount() {
    long cPtr = adioslibJNI._ADIOS_VARBLOCK_count_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setProcess_id(long value) {
    adioslibJNI._ADIOS_VARBLOCK_process_id_set(swigCPtr, this, value);
  }

  public long getProcess_id() {
    return adioslibJNI._ADIOS_VARBLOCK_process_id_get(swigCPtr, this);
  }

  public void setTime_index(long value) {
    adioslibJNI._ADIOS_VARBLOCK_time_index_set(swigCPtr, this, value);
  }

  public long getTime_index() {
    return adioslibJNI._ADIOS_VARBLOCK_time_index_get(swigCPtr, this);
  }

  public _ADIOS_VARBLOCK() {
    this(adioslibJNI.new__ADIOS_VARBLOCK(), true);
  }

}
