/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public enum ADIOS_READ_METHOD {
  ADIOS_READ_METHOD_BP(adioslibJNI.ADIOS_READ_METHOD_BP_get()),
  ADIOS_READ_METHOD_BP_AGGREGATE(adioslibJNI.ADIOS_READ_METHOD_BP_AGGREGATE_get()),
  ADIOS_READ_METHOD_DATASPACES(adioslibJNI.ADIOS_READ_METHOD_DATASPACES_get()),
  ADIOS_READ_METHOD_DIMES(adioslibJNI.ADIOS_READ_METHOD_DIMES_get()),
  ADIOS_READ_METHOD_FLEXPATH(adioslibJNI.ADIOS_READ_METHOD_FLEXPATH_get()),
  ADIOS_READ_METHOD_ICEE(adioslibJNI.ADIOS_READ_METHOD_ICEE_get());

  public final int swigValue() {
    return swigValue;
  }

  public static ADIOS_READ_METHOD swigToEnum(int swigValue) {
    ADIOS_READ_METHOD[] swigValues = ADIOS_READ_METHOD.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ADIOS_READ_METHOD swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ADIOS_READ_METHOD.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ADIOS_READ_METHOD() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ADIOS_READ_METHOD(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ADIOS_READ_METHOD(ADIOS_READ_METHOD swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

