/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public enum ADIOS_FLAG {
  adios_flag_unknown(adioslibJNI.adios_flag_unknown_get()),
  adios_flag_yes(adioslibJNI.adios_flag_yes_get()),
  adios_flag_no(adioslibJNI.adios_flag_no_get());

  public final int swigValue() {
    return swigValue;
  }

  public static ADIOS_FLAG swigToEnum(int swigValue) {
    ADIOS_FLAG[] swigValues = ADIOS_FLAG.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ADIOS_FLAG swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ADIOS_FLAG.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ADIOS_FLAG() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ADIOS_FLAG(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ADIOS_FLAG(ADIOS_FLAG swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

