/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public class ADIOS_HIST {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ADIOS_HIST(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADIOS_HIST obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        adioslibJNI.delete_ADIOS_HIST(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_breaks(long value) {
    adioslibJNI.ADIOS_HIST_num_breaks_set(swigCPtr, this, value);
  }

  public long getNum_breaks() {
    return adioslibJNI.ADIOS_HIST_num_breaks_get(swigCPtr, this);
  }

  public void setMax(double value) {
    adioslibJNI.ADIOS_HIST_max_set(swigCPtr, this, value);
  }

  public double getMax() {
    return adioslibJNI.ADIOS_HIST_max_get(swigCPtr, this);
  }

  public void setMin(double value) {
    adioslibJNI.ADIOS_HIST_min_set(swigCPtr, this, value);
  }

  public double getMin() {
    return adioslibJNI.ADIOS_HIST_min_get(swigCPtr, this);
  }

  public void setBreaks(SWIGTYPE_p_double value) {
    adioslibJNI.ADIOS_HIST_breaks_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getBreaks() {
    long cPtr = adioslibJNI.ADIOS_HIST_breaks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setFrequencies(SWIGTYPE_p_p_unsigned_int value) {
    adioslibJNI.ADIOS_HIST_frequencies_set(swigCPtr, this, SWIGTYPE_p_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_p_unsigned_int getFrequencies() {
    long cPtr = adioslibJNI.ADIOS_HIST_frequencies_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_unsigned_int(cPtr, false);
  }

  public void setGfrequencies(SWIGTYPE_p_unsigned_int value) {
    adioslibJNI.ADIOS_HIST_gfrequencies_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getGfrequencies() {
    long cPtr = adioslibJNI.ADIOS_HIST_gfrequencies_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public ADIOS_HIST() {
    this(adioslibJNI.new_ADIOS_HIST(), true);
  }

}
