/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public enum ADIOS_BUFFER_ALLOC_WHEN {
  ADIOS_BUFFER_ALLOC_UNKNOWN,
  ADIOS_BUFFER_ALLOC_NOW,
  ADIOS_BUFFER_ALLOC_LATER;

  public final int swigValue() {
    return swigValue;
  }

  public static ADIOS_BUFFER_ALLOC_WHEN swigToEnum(int swigValue) {
    ADIOS_BUFFER_ALLOC_WHEN[] swigValues = ADIOS_BUFFER_ALLOC_WHEN.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ADIOS_BUFFER_ALLOC_WHEN swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ADIOS_BUFFER_ALLOC_WHEN.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ADIOS_BUFFER_ALLOC_WHEN() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ADIOS_BUFFER_ALLOC_WHEN(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ADIOS_BUFFER_ALLOC_WHEN(ADIOS_BUFFER_ALLOC_WHEN swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

