/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public interface adioslibConstants {
  public final static int MPI_SUCCESS = adioslibJNI.MPI_SUCCESS_get();
  public final static int MPI_ERR_BUFFER = adioslibJNI.MPI_ERR_BUFFER_get();
  public final static int MPI_ERR_COUNT = adioslibJNI.MPI_ERR_COUNT_get();
  public final static int MPI_ERR_TYPE = adioslibJNI.MPI_ERR_TYPE_get();
  public final static int MPI_ERR_TAG = adioslibJNI.MPI_ERR_TAG_get();
  public final static int MPI_ERR_COMM = adioslibJNI.MPI_ERR_COMM_get();
  public final static int MPI_MAX_ERROR_STRING = adioslibJNI.MPI_MAX_ERROR_STRING_get();
  public final static int MPI_BYTE = adioslibJNI.MPI_BYTE_get();
  public final static int MPI_INFO_NULL = adioslibJNI.MPI_INFO_NULL_get();
  public final static int MPI_COMM_NULL = adioslibJNI.MPI_COMM_NULL_get();
  public final static int MPI_COMM_WORLD = adioslibJNI.MPI_COMM_WORLD_get();
  public final static int MPI_COMM_SELF = adioslibJNI.MPI_COMM_SELF_get();
  public final static int MPI_INT = adioslibJNI.MPI_INT_get();
  public final static int MPI_CHAR = adioslibJNI.MPI_CHAR_get();
  public final static int MPI_DOUBLE = adioslibJNI.MPI_DOUBLE_get();
  public final static int MPI_UINT64_T = adioslibJNI.MPI_UINT64_T_get();
  public final static int MPI_ANY_SOURCE = adioslibJNI.MPI_ANY_SOURCE_get();
  public final static int MPI_ANY_TAG = adioslibJNI.MPI_ANY_TAG_get();
  public final static int MPI_MAX_PROCESSOR_NAME = adioslibJNI.MPI_MAX_PROCESSOR_NAME_get();
}
