/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public class ADIOS_VARINFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ADIOS_VARINFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADIOS_VARINFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        adioslibJNI.delete_ADIOS_VARINFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVarid(int value) {
    adioslibJNI.ADIOS_VARINFO_varid_set(swigCPtr, this, value);
  }

  public int getVarid() {
    return adioslibJNI.ADIOS_VARINFO_varid_get(swigCPtr, this);
  }

  public void setType(ADIOS_DATATYPES value) {
    adioslibJNI.ADIOS_VARINFO_type_set(swigCPtr, this, value.swigValue());
  }

  public ADIOS_DATATYPES getType() {
    return ADIOS_DATATYPES.swigToEnum(adioslibJNI.ADIOS_VARINFO_type_get(swigCPtr, this));
  }

  public void setNdim(int value) {
    adioslibJNI.ADIOS_VARINFO_ndim_set(swigCPtr, this, value);
  }

  public int getNdim() {
    return adioslibJNI.ADIOS_VARINFO_ndim_get(swigCPtr, this);
  }

  public void setNsteps(int value) {
    adioslibJNI.ADIOS_VARINFO_nsteps_set(swigCPtr, this, value);
  }

  public int getNsteps() {
    return adioslibJNI.ADIOS_VARINFO_nsteps_get(swigCPtr, this);
  }

  public void setValue(SWIGTYPE_p_void value) {
    adioslibJNI.ADIOS_VARINFO_value_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getValue() {
    long cPtr = adioslibJNI.ADIOS_VARINFO_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setGlobal(int value) {
    adioslibJNI.ADIOS_VARINFO_global_set(swigCPtr, this, value);
  }

  public int getGlobal() {
    return adioslibJNI.ADIOS_VARINFO_global_get(swigCPtr, this);
  }

  public void setNblocks(SWIGTYPE_p_int value) {
    adioslibJNI.ADIOS_VARINFO_nblocks_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getNblocks() {
    long cPtr = adioslibJNI.ADIOS_VARINFO_nblocks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setSum_nblocks(int value) {
    adioslibJNI.ADIOS_VARINFO_sum_nblocks_set(swigCPtr, this, value);
  }

  public int getSum_nblocks() {
    return adioslibJNI.ADIOS_VARINFO_sum_nblocks_get(swigCPtr, this);
  }

  public void setNattrs(int value) {
    adioslibJNI.ADIOS_VARINFO_nattrs_set(swigCPtr, this, value);
  }

  public int getNattrs() {
    return adioslibJNI.ADIOS_VARINFO_nattrs_get(swigCPtr, this);
  }

  public void setAttr_ids(SWIGTYPE_p_int value) {
    adioslibJNI.ADIOS_VARINFO_attr_ids_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getAttr_ids() {
    long cPtr = adioslibJNI.ADIOS_VARINFO_attr_ids_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setStatistics(SWIGTYPE_p_ADIOS_VARSTAT value) {
    adioslibJNI.ADIOS_VARINFO_statistics_set(swigCPtr, this, SWIGTYPE_p_ADIOS_VARSTAT.getCPtr(value));
  }

  public SWIGTYPE_p_ADIOS_VARSTAT getStatistics() {
    long cPtr = adioslibJNI.ADIOS_VARINFO_statistics_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ADIOS_VARSTAT(cPtr, false);
  }

  public void setBlockinfo(SWIGTYPE_p_ADIOS_VARBLOCK value) {
    adioslibJNI.ADIOS_VARINFO_blockinfo_set(swigCPtr, this, SWIGTYPE_p_ADIOS_VARBLOCK.getCPtr(value));
  }

  public SWIGTYPE_p_ADIOS_VARBLOCK getBlockinfo() {
    long cPtr = adioslibJNI.ADIOS_VARINFO_blockinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ADIOS_VARBLOCK(cPtr, false);
  }

  public void setMeshinfo(SWIGTYPE_p_ADIOS_VARMESH value) {
    adioslibJNI.ADIOS_VARINFO_meshinfo_set(swigCPtr, this, SWIGTYPE_p_ADIOS_VARMESH.getCPtr(value));
  }

  public SWIGTYPE_p_ADIOS_VARMESH getMeshinfo() {
    long cPtr = adioslibJNI.ADIOS_VARINFO_meshinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ADIOS_VARMESH(cPtr, false);
  }

  public long getDims(int i) {
    return adioslibJNI.ADIOS_VARINFO_getDims(swigCPtr, this, i);
  }

  public ADIOS_VARINFO() {
    this(adioslibJNI.new_ADIOS_VARINFO(), true);
  }

}
