/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public enum ADIOS_LOCKMODE {
  ADIOS_LOCKMODE_NONE(adioslibJNI.ADIOS_LOCKMODE_NONE_get()),
  ADIOS_LOCKMODE_CURRENT(adioslibJNI.ADIOS_LOCKMODE_CURRENT_get()),
  ADIOS_LOCKMODE_ALL(adioslibJNI.ADIOS_LOCKMODE_ALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public static ADIOS_LOCKMODE swigToEnum(int swigValue) {
    ADIOS_LOCKMODE[] swigValues = ADIOS_LOCKMODE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ADIOS_LOCKMODE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ADIOS_LOCKMODE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ADIOS_LOCKMODE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ADIOS_LOCKMODE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ADIOS_LOCKMODE(ADIOS_LOCKMODE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

