/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ornl.adios.ext;

public class SWIGTYPE_p_ADIOS_VARSTAT {
  private transient long swigCPtr;

  protected SWIGTYPE_p_ADIOS_VARSTAT(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_ADIOS_VARSTAT() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_ADIOS_VARSTAT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

