#!/bin/sh
#PBS -N heat_adios_demo
#PBS -j oe
#PBS -l walltime=00:10:00,nodes=3:ppn=2

cd $PBS_O_WORKDIR
#mpirun -np 16 ./heat >& result.dat

#rm heat_adios_demo.o*
mpirun -np 6 heat_adios >& result.dat
