#!/bin/sh
#PBS -N heat_adios_demo
#PBS -j oe
#PBS -l walltime=00:05:00,nodes=8:ppn=2

cd $PBS_O_WORKDIR
#mpirun -np 16 ./heat >& result.dat

rm heat_adios_demo.o*
mpirun -np 16 ./heat_adios >& result.dat
